[package]
name = "termc_ui"
version = "0.1.0"
authors = ["jonas"]

[dependencies]
num = "0.1.37"

[target.'cfg(unix)'.dependencies]
termion = "1.3.0"

[dependencies.termc_model]
path = "../termc_model"