[package]
name = "termc_ui"
version = "0.1.0"
authors = ["jonas"]

[dependencies]
num = "0.1.37"
rustyline = "1.0.0"
app_dirs = "1.1.1"
colored = "1.5"

[dependencies.termc_model]
path = "../termc_model"